const fs = require('fs');

const userProvidedChannels = [
  // Page 1
  { name: "Star News", url: "https://owrcovcrpy.gpcdn.net/bpk-tv/1710/output/1701.m3u8" },
  { name: "TIME TV USA", url: "https://tvsen7.aynaott.com/timetv/index.m3u8" },
  { name: "Channel I", url: "https://tvsen6.aynaott.com/FNHpYvGZ7FkCE10PwTHm/index.m3u8" },
  { name: "NTV", url: "https://tvsen5.aynaott.com/xV4jEKf3D9zc/index.m3u8" },
  { name: "BTV NATIONAL HD", url: "https://tvsen6.aynaott.com/opREbXLqJ2HFYPCXTJBa/index.m3u8" },
  { name: "Bangla Vision", url: "https://tvsen5.aynaott.com/tgUzpPc9r6xw/index.m3u8" },
  { name: "ATN Bangla", url: "https://tvsen5.aynaott.com/P3y2URgG7LDe/index.m3u8" },
  { name: "RTV", url: "https://tvsen5.aynaott.com/ba47dHpDk3Se/index.m3u8" },
  { name: "Duronto TV", url: "https://tvsen6.aynaott.com/6xyZ3N4oHv2KBJdB6W4p/index.m3u8" },
  { name: "ETV", url: "https://tvsen5.aynaott.com/SyQuXz8sC3TB/index.m3u8" },
  { name: "Deepto TV", url: "https://tvsen5.aynaott.com/tK2BNdfsdfsdf/index.m3u8" },
  { name: "Ekhon TV", url: "https://tvsen6.aynaott.com/fbgZV3X17hwWcyfZ4pdb/index.m3u8" },
  { name: "Desh TV", url: "https://tvsen6.aynaott.com/ryFkXfd1a4CQ7mMdc820/index.m3u8" },
  { name: "Boishakhi TV", url: "https://tvsen6.aynaott.com/1d3uG9VCgrR9DRtWZM57/index.m3u8" },

  // Page 2
  { name: "Channel 9", url: "https://tvsen6.aynaott.com/kajlsd57jnkdf/index.m3u8" },
  { name: "SA TV", url: "https://tvsen6.aynaott.com/rELXiuUXqbgzPb06Npom/index.m3u8" },
  { name: "Bangla TV", url: "https://tvsen6.aynaott.com/39ee93nUbCCmm5LsyD4t/index.m3u8" },
  { name: "Mohona TV", url: "https://tvsen6.aynaott.com/AkyX5dunzju4cpo26dr7/index.m3u8" },
  { name: "NEXUS TV", url: "https://tvsen6.aynaott.com/Epm7WrFa/index.m3u8" },
  { name: "Bijoy TV", url: "https://tvsen6.aynaott.com/N8Xbo5vdwVU6sF43RsW0/index.m3u8" },
  { name: "Global TV", url: "https://tvsen6.aynaott.com/y0q9eFAuquAtvTxRzUHq/index.m3u8" },
  { name: "My TV", url: "https://tvsen6.aynaott.com/XMpHaEf0ANBhv8w6NWR7/index.m3u8" },
  { name: "Ananda TV", url: "https://tvsen6.aynaott.com/LeUAm4F1iixYns3s3Non/index.m3u8" },
  { name: "Green TV HD", url: "https://tvsen6.aynascope.net/cLuA3hJR/index.m3u8" },
  { name: "BTV World", url: "https://tvsen6.aynaott.com/AQLYTPfXtjm5x7zj7AsM/index.m3u8" },
  { name: "BTV CTG", url: "https://tvsen6.aynaott.com/TjGR1GcxKetHNVcMVxbq/index.m3u8" },
  { name: "R Plus", url: "https://tvsen6.aynaott.com/Xehy3ZqZ/index.m3u8" },
  { name: "Rupshi Bangla", url: "https://tvsen6.aynaott.com/a4L7Tcqv/index.m3u8" },
  { name: "Sangeet Bangla", url: "https://tvsen6.aynaott.com/hT5jHczt/index.m3u8" },
  { name: "News Time Bangla", url: "https://tvsen6.aynaott.com/xjkX3euD/index.m3u8" },

  // Page 3
  { name: "DW News", url: "https://tvsen6.aynaott.com/Qq3s5WR2/index.m3u8" },
  { name: "CNN", url: "https://tvsen6.aynaott.com/cnn/index.m3u8" },
  { name: "Bloomberg TV", url: "https://tvsen6.aynaott.com/bloombergtv/index.m3u8" },
  { name: "ABC News", url: "https://tvsen6.aynaott.com/ABCxzdsdNews/index.m3u8" },
  { name: "CNBC TV", url: "https://tvsen6.aynaott.com/cnbc/index.m3u8" },
  { name: "CP 24", url: "https://tvsen6.aynaott.com/cp24/index.m3u8" },
  { name: "Fox News", url: "https://tvsen6.aynaott.com/foxnews/index.m3u8" },
  { name: "Sky News", url: "https://tvsen5.aynaott.com/skynews/index.m3u8" },
  { name: "Somoy TV", url: "https://tvsen6.aynaott.com/4XcqdovJzbbC9WdJA9gk/index.m3u8" },
  { name: "ABN", url: "https://mediaserver.abnvideos.com/streams/abnurdu.m3u8" },
  { name: "India Today", url: "https://feeds.intoday.in/hltapps/api/master.m3u8" },
  { name: "Republic TV Bharat", url: "https://tvsen6.aynaott.com/faGd3tuq/index.m3u8" },
  { name: "News 1 India", url: "https://tvsen6.aynaott.com/TaVfw58T/index.m3u8" },
  { name: "Sadhna Prime News", url: "https://tvsen3.aynaott.com/P2hjvFHV/index.m3u8" },

  // Page 4
  { name: "Accu Weather", url: "https://cdn-ue1-prod.tsv2.amagi.tv/linear/amg00684-accuweather-accuweather-plex/playlist.m3u8" },
  { name: "Fox Weather", url: "https://247wlive.foxweather.com/stream/index.m3u8" },
  { name: "Sky News Weather", url: "https://distro001-gb-hls1-prd.delivery.skycdp.com/easel_cdn/ngrp:weather_loop.stream_all/playlist.m3u8" },
  { name: "Weather SPY", url: "https://jukin-weatherspy-2-in.samsung.wurl.tv/playlist.m3u8" },
  { name: "LIFE TIME", url: "https://tvsen7.aynaott.com/lifetime/index.m3u8" },
  { name: "TRT World", url: "https://tvsen7.aynaott.com/TRTWorldHD/index.m3u8" },
  { name: "MTV", url: "https://tvsen6.aynaott.com/mtv/index.m3u8" },
  { name: "Fox 5", url: "https://tvsen6.aynaott.com/fox5/index.m3u8" },
  { name: "Fox Business", url: "https://tvsen6.aynaott.com/foxbusiness/index.m3u8" },
  { name: "CBS TV", url: "https://tvsen3.aynaott.com/34fJSjZP/index.m3u8" },
  { name: "USA TV", url: "https://tvsen3.aynaott.com/dbbcY6NG/index.m3u8" },
  { name: "FX TV", url: "https://tvsen3.aynaott.com/jTqkTE8W/index.m3u8" },
  { name: "Weather Channel", url: "https://tvsen3.aynascope.net/uqXdx9CE/index.m3u8" },
  { name: "VTV USA", url: "https://tvsen7.aynaott.com/vtvusa/index.m3u8" },
  { name: "Wion", url: "https://d7x8z4yuq42qn.cloudfront.net/index_7.m3u8" },

  // Page 5
  { name: "News India 24x7", url: "https://tvsen3.aynaott.com/vG7Wpj7e/index.m3u8" },
  { name: "ABC 7 Bay", url: "https://content.uplynk.com/channel/ext/4413701bf5a1488db55b767f8ae9d4fa/kgo_24x7_news.m3u8" },
  { name: "FIFA+", url: "https://4397879b.wurl.com/master/f36d25e7e52f1ba8d7e56eb859c636563214f541/UmFrdXRlblRWLWRlX0ZJRkFQbHVzR2VybWFuX0hMUw/playlist.m3u8" },
  { name: "BTV National", url: "https://tvsen6.aynaott.com/opREbXLqJ2HFYPCXTJBa/index.m3u8" },
  { name: "Enter 10 Bangla", url: "https://live-bangla.akamaized.net/liveabr/playlist.m3u8" },
  { name: "Sony AATH", url: "https://live20.bozztv.com/giatvplayout7/giatv-209611/index.m3u8" },
  { name: "Thikana", url: "https://5dd3981940faa.streamlock.net:443/thikanatv/thikanatv/playlist.m3u8" },
  { name: "Cartoon Network", url: "https://tvsen3.aynascope.net/8PgGpDG5/index.m3u8" },
  { name: "And Pictures HD", url: "https://tvsen6.aynaott.com/andpictureshd/index.m3u8" },
  { name: "Zee 24 Ghanta", url: "https://tvsen6.aynaott.com/DpPnXP9r/index.m3u8" },
  { name: "Talk Sport", url: "https://tvsen6.aynaott.com/talkSPORT/index.m3u8" },
  { name: "B4U Hitz", url: "https://tvsen6.aynaott.com/B4UHitz/index.m3u8" },
  { name: "Dhoom Music Bangla", url: "https://tvsen6.aynaott.com/dhoom/index.m3u8" },
  { name: "Hindi Movie Classic 24", url: "https://vods2.aynaott.com/hindimovies/index.m3u8" },
  { name: "Drama 24", url: "https://vods2.aynaott.com/gseriesDrama/index.m3u8" },

  // Page 6
  { name: "Movie Bangla", url: "https://tvsen7.aynascope.net/moviebangla/index.m3u8" },
  { name: "Republic Bangla", url: "https://tvsen5.aynaott.com/qRHda6ax/index.m3u8" },
  { name: "Music India", url: "https://tvsen3.aynaott.com/Ydvf4ppw/index.m3u8" },
  { name: "Nickjr", url: "https://tvsen3.aynascope.net/LqCU7kXU/index.m3u8" },
  { name: "Peace TV Bangla HD", url: "https://tvsen3.aynaott.com/RxGdpyu5/index.m3u8" },
  { name: "Goldmines Bollywood", url: "https://tvsen6.aynaott.com/55xNrLdf/index.m3u8" },
  { name: "Deepto tv", url: "https://byphdgllyk.gpcdn.net/hls/deeptotv/index.m3u8" },
  { name: "DD Bangla", url: "https://d3qs3d2rkhfqrt.cloudfront.net/out/v1/7ff57cc9046b4c188b51a0d506f36e7f/index_3.m3u8" },
  { name: "Kolkata TV", url: "https://tvsen6.aynaott.com/kolkatatv/index.m3u8" },
  { name: "Sports Fishing TV", url: "https://streams2.sofast.tv/v1/master/611d79b11b77e2f571934fd80ca1413453772ac7/eea68b79-bfe2-451e-a227-d637a5b9548a/manifest.m3u8" },
  { name: "Discovery HD", url: "https://tvsen3.aynaott.com/Zht5VqBb/index.m3u8" },
  { name: "9XM", url: "https://tvsen3.aynaott.com/qCrLpS9v/index.m3u8" },
  { name: "Disney Junior", url: "https://tvsen3.aynascope.net/aM7qKqq7/index.m3u8" },
  { name: "Dubai Sports 1", url: "https://tvsen6.aynaott.com/dubaisports1/index.m3u8" },
  { name: "Goal TV", url: "https://streams2.sofast.tv/sofastplayout/WiseM3U8_1/master.m3u8" },

  // Page 7
  { name: "Disney Channel", url: "https://tvsen7.aynaott.com/disney/index.m3u8" },
  { name: "Nat Geo TV", url: "https://tvsen3.aynaott.com/7mm4pwCy/index.m3u8" },
  { name: "TV9 Bangla", url: "https://dyjmyiv3bp2ez.cloudfront.net/pub-iotv9banaen8yq/liveabr/playlist.m3u8" },
  { name: "Animal Planet HD", url: "https://tvsen3.aynaott.com/wpa56Uk3/index.m3u8" },
  { name: "Zoom TV", url: "https://live.zoomnews.info/live/Zoom_playlist.m3u8" },
  { name: "AMC", url: "https://tvsen6.aynaott.com/amc/index.m3u8" },
  { name: "Manoranjan Movies", url: "https://tvsen6.aynaott.com/vhu6qz5N/index.m3u8" },
  { name: "Goldmines Movies", url: "https://tvsen3.aynaott.com/5CGfPvGp/index.m3u8" },
  { name: "HBO", url: "https://tvsen7.aynaott.com/hbo/index.m3u8" },
  { name: "HBO 2", url: "https://tvsen3.aynaott.com/u3NjUrny/index.m3u8" }
];

console.log('Total user channels in list:', userProvidedChannels.length);
fs.writeFileSync('scripts/user_pdf_channels.json', JSON.stringify(userProvidedChannels, null, 2), 'utf8');
